"""Expanded healthcare room vocabulary: config, contract, generation, API.

Covers the three vocabulary tiers of the default config:
- allowed canonical vocabulary (`allowed_node_types`),
- default essential generated mix (grammar rules / `room_type_counts`),
- optional room types (allowed, requestable, not generated by default).
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

import pytest
import yaml
from fastapi.testclient import TestClient

import graph_layout_synth.grammar_variant_assistant as assistant
from graph_layout_synth.config import DEFAULT_CONFIG_PATH, load_config
from graph_layout_synth.config_contract import build_config_contract
from graph_layout_synth.generator import generate_candidate
from graph_layout_synth.grammar_variant_assistant import build_instruction_variant_prompt
from graph_layout_synth.grammar_variant_control_plane import (
    ENABLE_LLM_VARIANTS_ENV,
    LLM_VARIANT_DIR_ENV,
)
from graph_layout_synth.program_preflight import run_program_preflight
from server.main import create_app


PROJECT_ROOT = Path(__file__).resolve().parents[1]
GRAMMAR_SKILLS_PATH = PROJECT_ROOT / "docs/GRAMMAR_CONFIG_SKILLS.md"

ESSENTIAL_GENERATED_TYPES = {
    "PatientRoom",
    "OnStageCorridor",
    "OffStageCorridor",
    "NurseStation",
    "MedicationRoom",
    "CleanUtility",
    "SoiledUtility",
    "EquipmentRoom",
    "StorageRoom",
    "StaffLounge",
    "StaffToilet",
    "PublicToilet",
    "Stair",
    "Elevator",
    "MEPRoom",
    "UtilityRoom",
}

OPTIONAL_ROOM_TYPES = {
    "TeamRoom",
    "Office",
    "ConferenceRoom",
    "NourishmentRoom",
    "LinenRoom",
    "RespiratoryTherapyRoom",
    "PPEStorage",
    "ConsultRoom",
    "VisitorLounge",
    "FamilyRoom",
    "Dayroom",
    "DiningRoom",
    "ElectricalRoom",
    "MechanicalRoom",
    "TelecomRoom",
    "Kitchen",
}


def _raw_config() -> dict:
    return yaml.safe_load(Path(DEFAULT_CONFIG_PATH).read_text(encoding="utf-8"))


def _fail_if_called(*_args: object, **_kwargs: object) -> str:
    raise AssertionError("Claude must not be called in this scenario.")


# --- Allowed canonical vocabulary -----------------------------------------------


def test_allowed_node_types_include_expanded_and_optional_vocabulary():
    config = load_config(DEFAULT_CONFIG_PATH)

    allowed = set(config.allowed_node_types)
    assert ESSENTIAL_GENERATED_TYPES <= allowed
    assert OPTIONAL_ROOM_TYPES <= allowed
    # Legacy compatibility types stay allowed.
    assert {"Corridor", "ClinicalSupport", "StaffSupport"} <= allowed
    # Category names are semantic groups, never canonical graph node types.
    assert not {
        "Administration",
        "PatientSupport",
        "PublicAmenity",
        "Infrastructure",
    } & allowed
    # Node type IDs stay flat: no nested/dotted hierarchy.
    assert all("." not in node_type for node_type in allowed)


def test_semantic_groups_assign_new_types_to_expected_groups():
    contract = build_config_contract(_raw_config())

    groups = contract.semantic_node_groups
    for expected_group in (
        "room_like",
        "corridor",
        "patient",
        "patient_care",
        "administration",
        "clinical_support",
        "staff_support",
        "patient_support",
        "public_amenity",
        "vertical_circulation",
        "building_service",
        "support",
    ):
        assert expected_group in groups, expected_group

    assert set(groups["corridor"]) == {"Corridor", "OnStageCorridor", "OffStageCorridor"}
    assert groups["patient"] == ["PatientRoom"]
    assert {"Stair", "Elevator"} == set(groups["vertical_circulation"])
    assert "NurseStation" in groups["clinical_support"]
    assert "MEPRoom" in groups["building_service"]
    assert "StaffLounge" in groups["staff_support"]
    assert "VisitorLounge" in groups["public_amenity"]
    # Legacy support types stay members of their legacy groups.
    assert "ClinicalSupport" in groups["clinical_support"]
    assert "StaffSupport" in groups["staff_support"]
    assert {"ClinicalSupport", "StaffSupport"} <= set(groups["support"])
    assert not contract.errors


# --- ConfigContract / LLM prompt context ----------------------------------------


def test_contract_and_instruction_prompt_expose_expanded_vocabulary():
    raw_config = _raw_config()
    contract = build_config_contract(raw_config)

    assert "NurseStation" in contract.room_like_node_types
    assert "OnStageCorridor" in contract.corridor_node_types
    assert "MedicationRoom" in contract.support_node_types
    assert "balanced_each_to_one" in (
        contract.grammar_rule_schema_summary["supported_edge_modes"]
    )

    prompt = build_instruction_variant_prompt(
        raw_config,
        GRAMMAR_SKILLS_PATH.read_text(encoding="utf-8"),
        "Add a kitchen near the dining room.",
    )
    for node_type in ("NurseStation", "OnStageCorridor", "Stair", "Elevator", "Kitchen"):
        assert node_type in prompt, node_type
    assert "balanced_each_to_one" in prompt


# --- Default essential generated mix --------------------------------------------


def test_default_generation_produces_essential_mix_only():
    config = load_config(DEFAULT_CONFIG_PATH)
    result = generate_candidate(seed=42, config=config)

    assert result.is_valid
    type_counts = Counter(
        attrs.get("type") for _, attrs in result.graph.nodes(data=True)
    )
    generated_types = set(type_counts)
    assert ESSENTIAL_GENERATED_TYPES <= generated_types
    # Optional types are allowed but not generated by the default grammar.
    assert not OPTIONAL_ROOM_TYPES & generated_types
    # Legacy types are no longer generated by default.
    assert "Corridor" not in generated_types
    assert "ClinicalSupport" not in generated_types

    assert type_counts["OnStageCorridor"] == 4
    assert type_counts["OffStageCorridor"] == 1
    assert type_counts["NurseStation"] == 2
    assert type_counts["Stair"] == 2
    assert 20 <= type_counts["PatientRoom"] <= 24


def test_default_generation_balances_patients_across_nurse_stations():
    config = load_config(DEFAULT_CONFIG_PATH)
    result = generate_candidate(seed=42, config=config)

    nurse_loads = Counter()
    for left, right, attrs in result.graph.edges(data=True):
        if attrs.get("edge_type") != "door":
            continue
        types = {
            left: result.graph.nodes[left].get("type"),
            right: result.graph.nodes[right].get("type"),
        }
        if set(types.values()) == {"PatientRoom", "NurseStation"}:
            nurse = left if types[left] == "NurseStation" else right
            nurse_loads[nurse] += 1

    assert sum(nurse_loads.values()) >= 20
    assert all(load <= 12 for load in nurse_loads.values())


# --- Program requirements -------------------------------------------------------


def test_program_requirements_accept_new_canonical_types(monkeypatch):
    monkeypatch.setattr(assistant, "propose_grammar_variant_with_claude", _fail_if_called)
    requirements = {
        "schemaVersion": 1,
        "program": {
            "roomMix": {
                "PatientRoom": {"min": 10, "target": 12, "max": 14},
                "Stair": {"min": 2, "target": 2, "max": 2},
                "Elevator": {"min": 1, "target": 2, "max": 2},
                "MEPRoom": {"min": 1, "target": 1, "max": 2},
                "UtilityRoom": {"min": 1, "target": 2, "max": 3},
                "CleanUtility": {"min": 1, "target": 2, "max": 3},
                "MedicationRoom": {"min": 1, "target": 1, "max": 2},
            }
        },
    }

    result = run_program_preflight(requirements, raw_config=_raw_config())

    assert result.valid is True
    assert "UNKNOWN_ROOM_TYPE" not in {issue.code for issue in result.errors}


def test_program_requirements_reject_misspelled_type():
    requirements = {
        "schemaVersion": 1,
        "program": {"roomMix": {"NursStation": {"min": 1, "target": 1, "max": 1}}},
    }

    result = run_program_preflight(requirements, raw_config=_raw_config())

    assert result.valid is False
    assert "UNKNOWN_ROOM_TYPE" in {issue.code for issue in result.errors}


def test_program_requirements_validate_endpoint_accepts_new_types(monkeypatch):
    monkeypatch.setattr(assistant, "propose_grammar_variant_with_claude", _fail_if_called)
    client = TestClient(create_app())

    response = client.post(
        "/program-requirements/validate",
        json={
            "programRequirements": {
                "schemaVersion": 1,
                "program": {
                    "roomMix": {
                        "Stair": {"min": 2, "target": 2, "max": 2},
                        "CleanUtility": {"min": 1, "target": 2, "max": 3},
                    }
                },
            }
        },
    )

    assert response.status_code == 200
    assert response.json()["valid"] is True


# --- /suggest-next-room with the expanded default config ------------------------


def test_suggest_next_room_works_with_expanded_default_config(monkeypatch):
    monkeypatch.setattr(assistant, "propose_grammar_variant_with_claude", _fail_if_called)
    client = TestClient(create_app())

    response = client.post(
        "/suggest-next-room",
        json={
            "floorplan": {
                "schemaVersion": 1,
                "rooms": [
                    {
                        "id": "room-1",
                        "type": "OnStageCorridor",
                        "x": 100,
                        "y": 100,
                        "width": 300,
                        "height": 80,
                    },
                    {
                        "id": "room-2",
                        "type": "PatientRoom",
                        "x": 250,
                        "y": 200,
                        "width": 150,
                        "height": 110,
                    },
                ],
                "edges": [
                    {
                        "id": "edge-1",
                        "sourceRoomId": "room-1",
                        "targetRoomId": "room-2",
                        "edgeType": "door",
                    }
                ],
                "selectedRoomId": "room-1",
            },
            "anchorRoomId": "room-1",
            "sampleCount": 3,
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert isinstance(payload["suggestions"], list)
    assert payload["sampleCount"] == 3
    # Any suggested type must come from the canonical vocabulary.
    allowed = set(load_config(DEFAULT_CONFIG_PATH).allowed_node_types)
    assert all(item["roomType"] in allowed for item in payload["suggestions"])


# --- Instruction-guided variants ------------------------------------------------


def _propose_from_instructions(tmp_path, monkeypatch, proposed_config: dict):
    monkeypatch.setenv(ENABLE_LLM_VARIANTS_ENV, "true")
    monkeypatch.setenv(LLM_VARIANT_DIR_ENV, str(tmp_path / "llm-variants"))
    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key")
    monkeypatch.setattr(
        assistant,
        "propose_grammar_variant_with_claude",
        lambda prompt, model, max_tokens: (
            "Rationale.\n```yaml\n" + yaml.safe_dump(proposed_config, sort_keys=False) + "\n```"
        ),
    )
    client = TestClient(create_app())
    return client.post(
        "/grammar-variants/propose-from-instructions",
        json={"instructionText": "# Rules\n\n- Add a kitchen and dining wing.\n"},
    )


def test_instruction_variant_with_new_canonical_types_validates(tmp_path, monkeypatch):
    proposed = _raw_config()
    # Extend the service zone with optional room types from the vocabulary.
    service_rule = next(
        rule for rule in proposed["grammar_rules"] if rule["name"] == "expand_service_zone"
    )
    service_rule["action"]["create_nodes"].append(
        {
            "alias": "kitchen",
            "type": "Kitchen",
            "count": 1,
            "attributes": {"is_abstract": False},
        }
    )
    service_rule["action"]["create_edges"].append(
        {
            "source": "kitchen",
            "target": "offstage",
            "edge_type": "door",
            "mode": "each_to_one",
        }
    )

    response = _propose_from_instructions(tmp_path, monkeypatch, proposed)

    assert response.status_code == 200
    assert response.json()["valid"] is True


def test_instruction_variant_with_misspelled_type_fails_validation(tmp_path, monkeypatch):
    proposed = _raw_config()
    service_rule = next(
        rule for rule in proposed["grammar_rules"] if rule["name"] == "expand_service_zone"
    )
    service_rule["action"]["create_nodes"].append(
        {
            "alias": "kitchen",
            "type": "Kichen",
            "count": 1,
            "attributes": {"is_abstract": False},
        }
    )

    response = _propose_from_instructions(tmp_path, monkeypatch, proposed)

    assert response.status_code == 200
    payload = response.json()
    assert payload["valid"] is False
    assert payload["status"] == "proposed_invalid"


# --- Visualization --------------------------------------------------------------


def test_all_catalog_types_have_explicit_visualization_colors():
    config = load_config(DEFAULT_CONFIG_PATH)
    contract = build_config_contract(_raw_config())

    colored_types = set(config.visualization.node_colors)
    catalog_types = set(contract.room_like_node_types) | set(contract.corridor_node_types)
    missing = sorted(catalog_types - colored_types)
    assert missing == []
    hex_colors = config.visualization.node_colors.values()
    assert all(color.startswith("#") and len(color) == 7 for color in hex_colors)


def test_generated_graph_visualization_renders(tmp_path):
    pytest.importorskip("matplotlib")
    from graph_layout_synth.visualize import visualize_graph

    config = load_config(DEFAULT_CONFIG_PATH)
    result = generate_candidate(seed=42, config=config)

    output_path = visualize_graph(
        result.graph,
        tmp_path / "healthcare_default.png",
        config=config,
        title="Expanded vocabulary default candidate",
    )

    assert Path(output_path).is_file()
    assert Path(output_path).stat().st_size > 0
